// @todo - move data to api
export const simpleProjects: Record<string, string[]> = {
	"/bank-torun": ["index"],
	"/bioline": ["index", "cart", "product_cart", "products", "products_ingredients", "text"],
	"/dominplus": ["index"],
	"/grant-studio": ["index", "about-us", "contact", "offer", "realized", "realized-step"],
	"/kwiaciarnia": [
		"index",
		"koszyk",
		"podstrona_dodatki",
		"podstrona_dodatki_karta",
		"podstrona_kwiaty",
		"podstrona_kwiaty_karta",
		"podstrona_textowa",
		"podstrona_wyszukiwania",
	],
	"/melimelo": ["index"],
	"/poltrade": [
		"about_us",
		"contact",
		"index",
		"menu_with_tabs",
		"offer",
		"offer_text",
		"realized",
		"use_text",
		"use_image",
	],
	"/pozyczkafm": [
		"index",
		"index-calculator",
		"wnioski_kredytowe-01-weryfikacja",
		"wnioski_kredytowe-02-niepowodzenie",
		"wnioski_kredytowe-03-pozytywna",
		"wnioski_kredytowe-FAQ",
		"wnioski_kredytowe-kontakt",
		"wnioski_kredytowe-pozyczka",
		"wnioski_kredytowe-wniosek",
		"wnioski_kredytowe-wymogi",
	],
	"/pozyczkowo": [
		"index",
		"index-calculator",
		"wnioski_kredytowe-FAQ",
		"wnioski_kredytowe-kontakt",
		"wnioski_kredytowe-pozyczka",
		"wnioski_kredytowe-wniosek",
		"wnioski_kredytowe-wymogi",
	],
	"/salon": ["index"],
};
